INSERT INTO public."roomTypep" ("room_type_photo",
                                "room_type_description",
                                "quests_amount",
                                "room_type_name",
                                "room_type_price",
                                "availability",
                                "room_type_id",
                                "room_id",
                                "room_sqm",
                                "room_photo_des")
VALUES ('images/card-1.png',
        'CLASSIC ONE BEDROOM APARTMENT • 16 sq.m. • private bathroom • accommodates 2 people',
        2,
        'CLASSIC ONE BEDROOM',
        40,
        'true',
        3,
        3,
        16,
        'images/photos-des-classic.png'), ('images/card-2.png',
                                           'TRIPLE APARTMENT • 30 sq.m. • private bathroom • accommodates 3 people',
                                           3,
                                           'TRIPLE APARTMENT',
                                           55,
                                           'true',
                                           4,
                                           4,
                                           30,
                                           'images/photos-des-triple.png'), ('images/card-4.png',
                                                                             'ALL SPACE ROOM • 45 sq.m. • private bathroom • accommodates 4 people',
                                                                             4,
                                                                             'ALL SPACE ROOM',
                                                                             72,
                                                                             'true',
                                                                             5,
                                                                             5,
                                                                             72,
                                                                             'images/photos-des-all-space.png'), ('images/card-3.png',
                                                                                                                  'CITY ONE BEDROOM • 30 sq.m • private bathroom • accommodates 2 people',
                                                                                                                  2,
                                                                                                                  'CITY ONE BEDROOM',
                                                                                                                  45,
                                                                                                                  'true',
                                                                                                                  1,
                                                                                                                  1,
                                                                                                                  30,
                                                                                                                  'images/photos-des-city.png'), ('images/card-5.png',
                                                                                                                                                  'DOUBLE ROOM • 25 sq.m. • private bathroom • accommodates 2 people',
                                                                                                                                                  2,
                                                                                                                                                  'DOUBLE ROOM',
                                                                                                                                                  45,
                                                                                                                                                  'true',
                                                                                                                                                  2,
                                                                                                                                                  2,
                                                                                                                                                  25,
                                                                                                                                                  'images/photos-des-double.png');

-- INSERT INTO public."CLIENT" (full_name,
--                              email,
--                              phone_number,
--                              password)
-- VALUES ('user',
--         'u@u.com',
--         123456789,
--         '123');
